export const Formats: FormatList = [
	// Digimon Metas
	{
		section: "Digimon Random Battles",
		column: 1,
	},
	{
		name: "[Digimon] Random Battle",
		desc: "Battle and play with your friends with this Digimon & LGPE hyrbid.",
		mod: "digimon",
		team: "randomDigimon",
		ruleset: ['Standard'],
	},
	{
		name: "[Digimon] Random Doubles",
		desc: "Battle and play with your friends with this Digimon & LGPE hyrbid.",
		mod: "digimon",
		gameType: 'doubles',
		team: "randomDigimon",
		ruleset: ['Standard'],
	},
	{
		name: "[Digimon] Random Triples",
		desc: "Battle and play with your friends with this Digimon & LGPE hyrbid.",
		mod: "digimon",
		gameType: 'triples',
		team: "randomDigimon",
		ruleset: ['Standard'],
	},
	{
		name: "[Digimon] Random Monotype",
		desc: "Battle in this Digimon & LGPE Monotype format!",
		mod: "digimon",
		team: "randomDigimon",
		ruleset: ['Standard'],
	},
	{
		name: "[Digimon] Random Monotype Doubles",
		desc: "Battle in this Digimon & LGPE Monotype format!",
		mod: "digimon",
		gameType: 'doubles',
		team: "randomDigimon",
		ruleset: ['Standard'],
	},
	{
		name: "[Digimon] Digimon x Pokemon Random Battle",
		desc: "Worlds Collide in this Digimon & LGPE Format!",
		mod: "digimon",
		team: "randomDigimon",
		ruleset: ['Standard'],
	},
	{
		name: "[Digimon] Digimon x Pokemon Random Doubles",
		desc: "Worlds Collide in this Digimon & LGPE Format!",
		mod: "digimon",
		gameType: 'doubles',
		team: "randomDigimon",
		ruleset: ['Standard'],
	},
	{
		section: "Digimon Metas",
		column: 1,
	},
	{
		name: "[Gen 7 Let's Go] Digimon Singles",
		desc: "Singles Format",
		mod: "digimon",
		ruleset: ['Standard', 'Standard NEXT'],
	},
	{
		name: "[Gen 7 Let's Go] Digimon Doubles",
		desc: "Doubles Format",
		mod: "digimon",
		gameType: 'doubles',
		ruleset: ['Standard', 'Standard NEXT'],
	},
];
