export const Formats: FormatList = [
	// Digimon Metas
	{
		section: "Digimon Random Battles",
		column: 1,
	},
	{
		name: "[Digimon] Random Singles",
		desc: "Battle and play with your friends with this Digimon & LGPE hyrbid.",
		mod: "digimon",
		team: "randomDigimon",
		ruleset: ['Standard'],
	},
	{
		name: "[Digimon] Random Doubles",
		desc: "Battle and play with your friends with this Digimon & LGPE hyrbid.",
		mod: "digimon",
		gameType: 'doubles',
		team: "randomDigimon",
		ruleset: ['Standard'],
	},
	{
		name: "[Digimon] Random Triples",
		desc: "Battle and play with your friends with this Digimon & LGPE hyrbid.",
		mod: "digimon",
		gameType: 'triples',
		team: "randomDigimon",
		ruleset: ['Standard'],
	},
	{
		name: "[Digimon] Random Monotype",
		desc: "Battle in this Digimon & LGPE Monotype format!",
		mod: "digimon",
		team: "randomDigimon",
		ruleset: ['Standard'],
	},
	{
		name: "[Digimon] Random Monotype Doubles",
		desc: "Battle in this Digimon & LGPE Monotype format!",
		mod: "digimon",
		gameType: 'doubles',
		team: "randomDigimon",
		ruleset: ['Standard'],
	},
	{
		name: "[Digimon] Random Digimon x Pokemon",
		desc: "Worlds Collide in this Digimon & LGPE Format!",
		mod: "digimon",
		team: "randomDigimon",
		ruleset: ['Standard'],
	},
	{
		name: "[Digimon] Random Digimon x Pokemon Doubles",
		desc: "Worlds Collide in this Digimon & LGPE Format!",
		mod: "digimon",
		gameType: 'doubles',
		team: "randomDigimon",
		ruleset: ['Standard'],
	},
];
